### ISSUE TITLE
Better earthquake site for mobile

### ISSUE THREAD

**Issue by EstherDeLoof** [OpenWebslides/Velov2017#11]
I've added a better site for the earthquakes, one that allows for finger gestures on mobile.
@floriandejonckheere can you make sure it also displays via one of your proxys?

**Comment by floriandejonckheere** [comment]
I cannot proxy two root domains in the current setup (molview.org and earthquake3d.org), it would require a major overhaul.
I suggest using the previous one, so that attendees will at least be able to see it working.
